name: Unit Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13", "3.8", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint coverage
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py') --disable=C0301 --fail-under 9

    - name: Run unit tests with coverage
      run: |
        coverage run --source=cli,lib -m unittest test_cli_unit.py

    - name: Show coverage report
      run: |
        echo '### Coverage Report (Python ${{ matrix.python-version }})' >> $GITHUB_STEP_SUMMARY
        coverage report -m >> coverage.txt
        echo '```' >> $GITHUB_STEP_SUMMARY
        cat coverage.txt >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
